server:
  port: 1024


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myprogram?characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root

  mvc:
    static-path-pattern: /**

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/



